/**
 * 菜单图标库
 */
 import React from 'react';
import { createFromIconfontCN } from '@ant-design/icons';
import * as Icons from '@ant-design/icons';

//使用试例: <Icon type="icon-system" style={{ fontSize: '16px', color: '#08c' }} />
const Icon = createFromIconfontCN({
  scriptUrl: ['//at.alicdn.com/t/font_2546793_9mt1zfi2wcn.js'],
});

/**方向性图标关键字 */
const directionIcons = [
  'step-backward',
  'step-forward',
  'fast-backward',
  'fast-forward',
  'shrink',
  'arrows-alt',
  'down',
  'up',
  'left',
  'right',
  'caret-up',
  'caret-down',
  'caret-left',
  'caret-right',
  'up-circle',
  'down-circle',
  'left-circle',
  'right-circle',
  'up-circle-o',
  'down-circle-o',
  'right-circle-o',
  'left-circle-o',
  'double-right',
  'double-left',
  'vertical-left',
  'vertical-right',
  'forward',
  'backward',
  'rollback',
  'enter',
  'retweet',
  'swap',
  'swap-left',
  'swap-right',
  'arrow-up',
  'arrow-down',
  'arrow-left',
  'arrow-right',
  'play-circle',
  'play-circle-o',
  'up-square',
  'down-square',
  'left-square',
  'right-square',
  'up-square-o',
  'down-square-o',
  'left-square-o',
  'right-square-o',
  'login',
  'logout',
  'menu-fold',
  'menu-unfold',
  'border-bottom',
  'border-horizontal',
  'border-inner',
  'border-left',
  'border-right',
  'border-top',
  'border-verticle',
  'pic-center',
  'pic-left',
  'pic-right',
  'radius-bottomleft',
  'radius-bottomright',
  'radius-upleft',
  'radius-upright',
  'fullscreen',
  'fullscreen-exit',
];

/**指示性图标关键字 */
const suggestionIcons = [
  'question',
  'question-circle',
  'plus',
  'plus-circle',
  'pause',
  'pause-circle',
  'minus',
  'minus-circle',
  'plus-square',
  'minus-square',
  'info',
  'info-circle',
  'exclamation',
  'exclamation-circle',
  'close',
  'close-circle',
  'close-square',
  'check',
  'check-circle',
  'check-square',
  'clock-circle',
  'warning',
  'issues-close',
  'stop',
];
/**编辑类图标关键字 */
const editIcons = [
  'edit',
  'form',
  'copy',
  'scissor',
  'delete',
  'snippets',
  'diff',
  'highlight',
  'align-center',
  'align-left',
  'align-right',
  'bg-colors',
  'bold',
  'italic',
  'underline',
  'strikethrough',
  'redo',
  'undo',
  'zoom-in',
  'zoom-out',
  'font-colors',
  'font-size',
  'line-height',
  'colum-height',
  'dash',
  'small-dash',
  'sort-ascending',
  'sort-descending',
  'drag',
  'ordered-list',
  'radius-setting',
];
/**数据类图标 */
const dataIcons = [
  'area-chart',
  'pie-chart',
  'bar-chart',
  'dot-chart',
  'line-chart',
  'radar-chart',
  'heat-map',
  'fall',
  'rise',
  'stock',
  'box-plot',
  'fund',
  'sliders',
];
/**网站通用图标 */
const webIcons = [
  'group',
  'bug',
  'console-sql',
  'control',
  'ci',
  'account-book',
  'aim',
  'lock',
  'unlock',
  'bars',
  'book',
  'calendar',
  'cloud',
  'cloud-download',
  'code',
  'copy',
  'credit-card',
  'delete',
  'desktop',
  'download',
  'ellipsis',
  'file',
  'file-text',
  'file-unknown',
  'file-pdf',
  'file-word',
  'file-excel',
  'file-jpg',
  'file-ppt',
  'file-markdown',
  'file-add',
  'folder',
  'folder-open',
  'folder-add',
  'hdd',
  'frown',
  'meh',
  'smile',
  'inbox',
  'laptop',
  'appstore',
  'link',
  'mail',
  'mobile',
  'notification',
  'paper-clip',
  'picture',
  'poweroff',
  'reload',
  'search',
  'setting',
  'share-alt',
  'shopping-cart',
  'tablet',
  'tag',
  'tags',
  'to-top',
  'upload',
  'user',
  'video-camera',
  'home',
  'loading',
  'loading-3-quarters',
  'cloud-upload',
  'star',
  'heart',
  'environment',
  'eye',
  'camera',
  'save',
  'team',
  'solution',
  'phone',
  'filter',
  'exception',
  'export',
  'customer-service',
  'qrcode',
  'scan',
  'like',
  'dislike',
  'message',
  'pay-circle',
  'calculator',
  'pushpin',
  'bulb',
  'select',
  'switcher',
  'rocket',
  'bell',
  'disconnect',
  'database',
  'compass',
  'barcode',
  'hourglass',
  'key',
  'flag',
  'layout',
  'printer',
  'sound',
  'usb',
  'skin',
  'tool',
  'sync',
  'wifi',
  'car',
  'schedule',
  'user-add',
  'user-delete',
  'usergroup-add',
  'usergroup-delete',
  'man',
  'woman',

  'shop',
  'gift',
  'idcard',
  'medicine-box',
  'red-envelope',
  'coffee',
  'copyright',
  'trademark',
  'safety',
  'wallet',
  'bank',
  'trophy',
  'contacts',
  'global',
  'shake',
  'api',
  'fork',
  'dashboard',
  'table',
  'profile',
  'alert',
  'audit',
  'branches',
  'build',
  'border',
  'crown',
  'experiment',
  'fire',
  'money-collect',
  'property-safety',
  'read',
  'reconciliation',
  'rest',
  'security-scan',
  'insurance',
  'interation',
  'safety-certificate',
  'project',
  'thunderbolt',
  'block',
  'cluster',
  'deployment-unit',
  'dollar',
  'euro',
  'pound',
  'file-done',
  'file-exclamation',
  'file-protect',
  'file-search',
  'file-sync',
  'gateway',
  'gold',
  'robot',
  'shopping',
];
/**品牌和标识 */
const logoIcons = [
  'android',
  'apple',
  'windows',
  'ie',
  'chrome',
  'github',
  'aliwangwang',
  'dingding',
  'weibo-square',
  'weibo-circle',
  'taobao-circle',
  'html5',
  'weibo',
  'twitter',
  'wechat',
  'youtube',
  'alipay-circle',
  'taobao',
  'skype',
  'qq',
  'medium-workmark',
  'gitlab',
  'medium',
  'linkedin',
  'google-plus',
  'dropbox',
  'facebook',
  'codepen',
  'amazon',
  'google',
  'codepen-circle',
  'alipay',
  'ant-design',
  'aliyun',
  'zhihu',
  'slack',
  'slack-square',
  'behance',
  'behance-square',
  'dribbble',
  'dribbble-square',
  'instagram',
  'yuque',
  'alibaba',
  'yahoo',
];

/**网站通用图标 */
const webIconData = {
  group: <Icons.GroupOutlined />,
  compass: <Icons.CompassOutlined />,
  bug: <Icons.BugOutlined />,
  'console-sql': <Icons.ConsoleSqlOutlined />,
  control: <Icons.ControlOutlined />,
  ci: <Icons.CiOutlined />,
  bell: <Icons.BellOutlined />,
  read: <Icons.ReadOutlined />,
  mail: <Icons.MailOutlined />,
  'deployment-unit': <Icons.DeploymentUnitOutlined />,
  cluster: <Icons.ClusterOutlined />,
  star: <Icons.StarOutlined />,
  team: <Icons.TeamOutlined />,
  project: <Icons.ProjectOutlined />,
  idcard: <Icons.IdcardOutlined />,
  lock: <Icons.LockOutlined />,
  unlock: <Icons.UnlockOutlined />,
  bars: <Icons.BarsOutlined />,
  book: <Icons.BookOutlined />,
  calendar: <Icons.CalendarOutlined />,
  audit: <Icons.AuditOutlined />,
  dashboard: <Icons.DashboardOutlined />,
  schedule: <Icons.ScheduleOutlined />,
  setting: <Icons.SettingOutlined />,
  home: <Icons.HomeOutlined />,
  table: <Icons.TableOutlined />,
  'video-camera': <Icons.VideoCameraOutlined />,
  smile: <Icons.SmileOutlined />,
  'security-scan': <Icons.SecurityScanOutlined />,
  alert: <Icons.AlertOutlined />,
  aim: <Icons.AimOutlined />,
  'account-book': <Icons.AccountBookOutlined />,
  camera: <Icons.CameraOutlined />,
  cloud: <Icons.CloudOutlined />,
  message: <Icons.MessageOutlined />,
  qrcode: <Icons.QrcodeOutlined />,
  profile: <Icons.ProfileOutlined />,
  user: <Icons.UserOutlined />,
  crown: <Icons.CrownOutlined />,
  thunderbolt: <Icons.ThunderboltOutlined />,
  'cloud-download': <Icons.CloudDownloadOutlined />,
  code: <Icons.CodeOutlined />,
  'credit-card': <Icons.CreditCardOutlined />,
  delete: <Icons.DeleteOutlined />,
  desktop: <Icons.DesktopOutlined />,
  download: <Icons.DownloadOutlined />,
  ellipsis: <Icons.EllipsisOutlined />,
  contacts: <Icons.ContactsOutlined />,

  file: <Icons.FileOutlined />,
  'file-text': <Icons.FileTextOutlined />,
  'file-unknown': <Icons.FileUnknownOutlined />,
  'file-pdf': <Icons.FilePdfOutlined />,
  'file-word': <Icons.FileWordOutlined />,
  'file-excel': <Icons.FileExcelOutlined />,
  'file-jpg': <Icons.FileJpgOutlined />,
  'file-ppt': <Icons.FilePptOutlined />,
  'file-markdown': <Icons.FileMarkdownOutlined />,
  'file-add': <Icons.FileAddOutlined />,
  'folder': <Icons.FolderOutlined />,
  'folder-open': <Icons.FolderOpenOutlined />,
  'folder-add': <Icons.FolderAddOutlined />,

  hdd: <Icons.HddOutlined />,
  frown: <Icons.FrownOutlined />,
  meh: <Icons.MehOutlined />,
  inbox: <Icons.InboxOutlined />,
  laptop: <Icons.LaptopOutlined />,
  appstore: <Icons.AppstoreOutlined />,
  link: <Icons.LinkOutlined />,
  mobile: <Icons.MobileOutlined />,
  notification: <Icons.NotificationOutlined />,
  'paper-clip': <Icons.PaperClipOutlined />,
  picture: <Icons.PictureOutlined />,
  poweroff: <Icons.PoweroffOutlined />,
  reload: <Icons.ReloadOutlined />,
  'share-alt': <Icons.ShareAltOutlined />,
  'shopping-cart': <Icons.ShoppingCartOutlined />,
  tablet: <Icons.TabletOutlined />,
  tag: <Icons.TagOutlined />,
  tags: <Icons.TagsOutlined />,
  'to-top': <Icons.ToTopOutlined />,
  upload: <Icons.UploadOutlined />,
  loading: <Icons.LoadingOutlined />,
  'loading-3-quarters': <Icons.Loading3QuartersOutlined />,
  'cloud-upload': <Icons.CloudUploadOutlined />,
  heart: <Icons.HeartOutlined />,
  environment: <Icons.EnvironmentOutlined />,
  eye: <Icons.EyeOutlined />,
  save: <Icons.SaveOutlined />,
  solution: <Icons.SolutionOutlined />,
  phone: <Icons.PhoneOutlined />,
  filter: <Icons.FilterOutlined />,
  exception: <Icons.ExceptionOutlined />,
  export: <Icons.ExportOutlined />,
  'customer-service': <Icons.CustomerServiceOutlined />,
  scan: <Icons.ScanOutlined />,
  like: <Icons.LikeOutlined />,
  dislike: <Icons.DislikeOutlined />,
  'pay-circle': <Icons.PayCircleOutlined />,
  calculator: <Icons.CalculatorOutlined />,
  pushpin: <Icons.PushpinOutlined />,
  bulb: <Icons.BulbOutlined />,
  select: <Icons.SelectOutlined />,
  switcher: <Icons.SwitcherOutlined />,
  rocket: <Icons.RocketOutlined />,
  disconnect: <Icons.DisconnectOutlined />,
  database: <Icons.DatabaseOutlined />,
  barcode: <Icons.BarcodeOutlined />,
  hourglass: <Icons.HourglassOutlined />,
  key: <Icons.KeyOutlined />,
  flag: <Icons.FlagOutlined />,
  layout: <Icons.LayoutOutlined />,
  printer: <Icons.PrinterOutlined />,
  sound: <Icons.SoundOutlined />,
  usb: <Icons.UsbOutlined />,
  skin: <Icons.SkinOutlined />,
  tool: <Icons.ToolOutlined />,
  wifi: <Icons.WifiOutlined />,
  car: <Icons.CarOutlined />,
  'user-add': <Icons.FlagOutlined />,
  'user-delete': <Icons.UserAddOutlined />,
  'usergroup-add': <Icons.UsergroupAddOutlined />,
  'usergroup-delete': <Icons.UsergroupDeleteOutlined />,
  man: <Icons.ManOutlined />,
  woman: <Icons.WomanOutlined />,
  shop: <Icons.ShopOutlined />,
  'money-collect': <Icons.MoneyCollectOutlined />,
};
/**数据类图标 */
const dataIconData = {
  'area-chart': <Icons.AreaChartOutlined />,
  'pie-chart': <Icons.PieChartOutlined />,
  'bar-chart': <Icons.BarChartOutlined />,
  'dot-chart': <Icons.DotChartOutlined />,
  'line-chart': <Icons.LineChartOutlined />,
  'radar-chart': <Icons.RadarChartOutlined />,
  'heat-map': <Icons.HeatMapOutlined />,
  fall: <Icons.FallOutlined />,
  rise: <Icons.RiseOutlined />,
  stock: <Icons.StockOutlined />,
  'box-plot': <Icons.BoxPlotOutlined />,
  fund: <Icons.FundOutlined />,
  sliders: <Icons.SlidersOutlined />,
};
/**指示性图标 */
const suggestionIconData = {
  'check-circle': <Icons.CheckCircleOutlined />,
  warning: <Icons.WarningOutlined />,
};
/**编辑类图标 */
const editIconData = {
  form: <Icons.FormOutlined />,
};
/**方向性图标 */
const directionIconData = {
  login: <Icons.LoginOutlined />,
  logout: <Icons.LogoutOutlined />,
  'step-backward': <Icons.StepBackwardOutlined />,
  'step-forward': <Icons.StepForwardOutlined />,
  'fast-backward': <Icons.FastBackwardOutlined />,
  'fast-forward': <Icons.FastForwardOutlined />,
  shrink: <Icons.ShrinkOutlined />,
  'arrows-alt': <Icons.ArrowsAltOutlined />,
  down: <Icons.DownOutlined />,
  up: <Icons.UpOutlined />,
  left: <Icons.LeftOutlined />,
  right: <Icons.RightOutlined />,
  'caret-up': <Icons.CaretUpOutlined />,
  'caret-down': <Icons.CaretDownOutlined />,
  'caret-left': <Icons.CaretLeftOutlined />,
  'caret-right': <Icons.CaretRightOutlined />,
  'up-circle': <Icons.UpCircleOutlined />,
  'down-circle': <Icons.DownCircleOutlined />,
  'left-circle': <Icons.LeftCircleOutlined />,
  'right-circle': <Icons.RightCircleOutlined />,
};

/**品牌和标识 */
const logoData = {
  'wechat': <Icons.WechatOutlined />,
  'alipay': <Icons.AlipayOutlined />,
  'qq': <Icons.QqOutlined />,
}

/**全部图标 */
const iconData = {
  // 'unlock':<Icons. />,

  ...webIconData, //网站通用图标
  ...dataIconData, //数据类图标
  ...suggestionIconData, //指示性图标
  ...editIconData, //编辑类图标
  ...directionIconData, //方向性图标
  ...logoData,
};

export {
  directionIcons,
  suggestionIcons,
  editIcons,
  dataIcons,
  webIcons,
  logoIcons,
  webIconData,
  dataIconData,
  suggestionIconData,
  editIconData,
  directionIconData,
  iconData,
  logoData
};
